default: &default
  adapter:  postgresql
  encoding: unicode
  host:     localhost
  username: admin
  password: root

development:
  <<: *default
  database: oivan

test:
  <<: *default
  database: oivan_test

production:
  <<: *default
  database: <%= ENV['DATABASE_URL'] %>
